ecompress: honour the exit status value of guess_suffix()
Presently, the 'PORTAGE_COMPRESS_SUFFIX' variable is assigned by way of
a command substitution in which the guess_suffix() function is called.
However, the variable is simultaneously exported, duly defeating the
error check. The issue is that the value of the '?' parameter will be
the exit status value of the export builtin, which will never fail.
Address this issue by exporting the variable as a separate step.

Further, ensure that die() throws a meaningful exception in the event
that the call to guest_suffix() does fail.

Signed-off-by: Kerin Millar <kfm@plushkava.net>
Signed-off-by: Sam James <sam@gentoo.org>

diff --git a/bin/ecompress b/bin/ecompress
--- a/bin/ecompress
+++ b/bin/ecompress
@@ -159,7 +159,10 @@ guess_suffix() {
 }
 
 # figure out the new suffix
-export PORTAGE_COMPRESS_SUFFIX=$(guess_suffix) || die
+if ! PORTAGE_COMPRESS_SUFFIX=$(guess_suffix); then
+	die "Failed to determine the suffix of archives created by ${PORTAGE_COMPRESS@Q}"
+fi
+export PORTAGE_COMPRESS_SUFFIX
 
 fix_symlinks() {
 	# Repeat until nothing changes, in order to handle multiple
