emerge-webrsync: simplify the tests for emerge and portageq
Presently, emerge-webrsync tries to locate the emerge and portageq
binaries by capturing the output of type -P then testing whether the
output was empty. Simplify these tests by acting upon the exit status of
the type builtin itself.

Signed-off-by: Kerin Millar <kfm@plushkava.net>
Signed-off-by: Sam James <sam@gentoo.org>

diff --git a/bin/emerge-webrsync b/bin/emerge-webrsync
--- a/bin/emerge-webrsync
+++ b/bin/emerge-webrsync
@@ -606,10 +606,12 @@ do_latest_snapshot() {
 
 # Use emerge and portageq from the same directory/prefix as the current script,
 # so that we don't have to rely on PATH including the current EPREFIX.
-emerge=$(PATH="${BASH_SOURCE[0]%/*}:${PATH}" type -P emerge)
-[[ -n ${emerge} ]] || die "could not find 'emerge'; aborting"
-portageq=$(PATH="${BASH_SOURCE[0]%/*}:${PATH}" type -P portageq)
-[[ -n ${portageq} ]] || die "could not find 'portageq'; aborting"
+if ! emerge=$(PATH=${BASH_SOURCE%/*}:${PATH} type -P emerge); then
+	die "could not find 'emerge'; aborting"
+fi
+if ! portageq=$(PATH=${BASH_SOURCE%/*}:${PATH} type -P portageq); then
+	die "could not find 'portageq'; aborting"
+fi
 
 eval "$("${portageq}" envvar -v DISTDIR EPREFIX FEATURES \
 	FETCHCOMMAND GENTOO_MIRRORS \
