emerge-webrsync: show a diagnostic if the key fingerprint can't be found
Presently, the check_file_signature_gpg() function will create an
ephemeral keyring in the case that the 'PORTAGE_GPG_DIR' variable is
unset or empty. It then proceeds to import Gentoo's public key block
from "gentoo-release.asc" and search for the fingerprint of the
<intrastructure@gentoo.org> key before designating the key as being
ultimately trusted.

However, should that search find nothing, the program will exit without
explaining what went wrong. Address this issue by invoking die() in the
case that the search fails. The resulting diagnostic is depicted below.

 * Checking signature ...
emerge-webrsync: couldn't find a fingerprint for the <infrastructure@gentoo.org> key

See-also: 2fa73d4e9f789db6cc8f261deea7f3d06f2fd4bb
Signed-off-by: Kerin Millar <kfm@plushkava.net>
Signed-off-by: Sam James <sam@gentoo.org>

diff --git a/bin/emerge-webrsync b/bin/emerge-webrsync
--- a/bin/emerge-webrsync
+++ b/bin/emerge-webrsync
@@ -305,9 +305,14 @@ check_file_signature_gpg() (
 		GNUPGHOME=$(mktemp -d -- "${PORTAGE_TMPDIR}/portage/webrsync.XXXXXX") \
 		&& trap 'gpgconf -K pgp-agent' EXIT \
 		&& gpg --batch --import "${key}" \
-		&& fingerprint=$(gpg_fingerprint '<infrastructure@gentoo.org>') \
-		&& gpg --batch --import-ownertrust <<<"${fingerprint}:6:" \
 		|| exit
+
+		# Obtain the fingerprint of the applicable signing key.
+		fingerprint=$(gpg_fingerprint '<infrastructure@gentoo.org>') \
+		|| die "couldn't find a fingerprint for the <infrastructure@gentoo.org> key"
+
+		# Designate the key as being ultimately trusted.
+		gpg --batch --import-ownertrust <<<"${fingerprint}:6:" || exit
 	elif [[ ! -w ${GNUPGHOME} ]]; then
 		die "gpgdir is not writable: ${GNUPGHOME}"
 	fi
