emerge-webrsync: clarify behaviour where gpg(1) is missing
Presently, the check_file_signature_gpg_unwrapped() function checks
whether gpg(1) is in PATH. In order to find out what happens in the case
that the check fails, it is necessary to read a comparatively long
branch of code. Remedy this by inverting the sense of the test and
making it clear that an exception shall be thrown where gpg(1) is found
to be missing.

Signed-off-by: Kerin Millar <kfm@plushkava.net>
Signed-off-by: Sam James <sam@gentoo.org>

diff --git a/bin/emerge-webrsync b/bin/emerge-webrsync
--- a/bin/emerge-webrsync
+++ b/bin/emerge-webrsync
@@ -288,7 +288,9 @@ check_file_signature_gpg_unwrapped() {
 	local -x GNUPGHOME
 	local key
 
-	if type -P gpg > /dev/null; then
+	if ! type -P gpg > /dev/null; then
+		die "cannot check signature: gpg binary not found"
+	else
 		if [[ -n ${PORTAGE_GPG_KEY} ]] ; then
 			key="${PORTAGE_GPG_KEY}"
 		else
@@ -318,8 +320,6 @@ check_file_signature_gpg_unwrapped() {
 			# problem).
 			die "signature verification failed"
 		fi
-	else
-		die "cannot check signature: gpg binary not found"
 	fi
 }
 
