Merged from trunk 8123:8140
   | 8124    | Add a note to clarify os.walk() behavior with respect to     |
   | zmedico | symlinks to directories.                                     |
   
   | 8125    | Sort the modes in the repoman --help output.                 |
   | zmedico |                                                              |
   
   | 8126    | Document the "manifest" mode.                                |
   | zmedico |                                                              |
   
   | 8128    | remove unused tmpfs variable                                 |
   | genone  |                                                              |
   
   | 8129    | Bug #195949 - Use a different diff_command sanity check when |
   | zmedico | using_editor is true.                                        |
   
   | 8130    | Bug #195949 - Add one more using_editor conditional for      |
   | zmedico | diff_command.                                                |
   
   | 8136    | Update NOTE_2 to document proper use of the using_editor     |
   | zmedico | config option.                                               |
   
   | 8138    | Update emacs and vim docs to reference NOTE_2.               |
   | zmedico |                                                              |
   
   | 8140    | Fix --help summary so that "commit" mode shows.              |
   | zmedico |                                                              |

svn path=/main/branches/prefix/; revision=8203

diff --git a/bin/etc-update b/bin/etc-update
--- a/bin/etc-update
+++ b/bin/etc-update
@@ -412,8 +412,16 @@ Please select from the menu above (-1 to exit, losing this merge): "
 				   rm ${rm_opts} "${file}"
 				   return 255
 				   ;;
-				2) ( echo "Showing differences between ${ofile} and ${mfile}"
-					 diff_command "${ofile}" "${mfile}" ) | ${pager}
+				2)	if [ "${using_editor}" == 0 ]; then
+						(
+							echo "Showing differences between ${ofile} and ${mfile}"
+							diff_command "${ofile}" "${mfile}"
+						) | ${pager}
+					else
+						echo "Beginning of differences between ${ofile} and ${mfile}"
+						diff_command "${ofile}" "${mfile}"
+						echo "End of differences between ${ofile} and ${mfile}"
+					fi
 				   continue
 				   ;;
 				3) break
@@ -520,13 +528,20 @@ declare -i mode=$(get_config mode)
 [[ -z ${mode} ]] && mode=0
 [[ -z ${pager} ]] && pager="cat"
 
-# Sanity check to make sure diff exists and works
-echo > "${TMP}"/.diff-test-1
-echo > "${TMP}"/.diff-test-2
-
-if ! diff_command "${TMP}"/.diff-test-1 "${TMP}"/.diff-test-2 &> /dev/null ; then
-	echo "ERROR: '${diff_command}' does not seem to work, aborting"
-	exit 1
+if [ "${using_editor}" == 0 ]; then
+	# Sanity check to make sure diff exists and works
+	echo > "${TMP}"/.diff-test-1
+	echo > "${TMP}"/.diff-test-2
+	
+	if ! diff_command "${TMP}"/.diff-test-1 "${TMP}"/.diff-test-2 ; then
+		echo "ERROR: '${diff_command}' does not seem to work, aborting"
+		exit 1
+	fi
+else
+	if ! type ${diff_command%% *} >/dev/null; then
+		echo "ERROR: '${diff_command}' does not seem to work, aborting"
+		exit 1
+	fi
 fi
 
 #echo "rm_opts: $rm_opts, mv_opts: $mv_opts, cp_opts: $cp_opts"
