install-qa-checks.d: fix 90gcc-warnings for other 64-bit arches
We were missing:
- aarch64*
- arm64* (Apple uses this for arm64)
- loongarch64*
- riscv64*
- s390x*

Signed-off-by: Sam James <sam@gentoo.org>

diff --git a/bin/install-qa-check.d/90gcc-warnings b/bin/install-qa-check.d/90gcc-warnings
--- a/bin/install-qa-check.d/90gcc-warnings
+++ b/bin/install-qa-check.d/90gcc-warnings
@@ -113,25 +113,26 @@ gcc_warn_check() {
 		fi
 
 		local cat_cmd=cat
-		[[ $PORTAGE_LOG_FILE = *.gz ]] && cat_cmd=zcat
-		[[ $reset_debug = 1 ]] && set -x
-		# Use safe cwd, avoiding unsafe import for bug #469338.
-		f=$(cd "${PORTAGE_PYM_PATH}" ; $cat_cmd "${PORTAGE_LOG_FILE}" | \
-			"${PORTAGE_PYTHON:-/usr/bin/python}" "$PORTAGE_BIN_PATH"/check-implicit-pointer-usage.py || die "check-implicit-pointer-usage.py failed")
-		if [[ -n ${f} ]] ; then
+		[[ ${PORTAGE_LOG_FILE} = *.gz ]] && cat_cmd=zcat
+		[[ ${reset_debug} = 1 ]] && set -x
 
+		# Use safe cwd, avoiding unsafe import for bug #469338.
+		f=$(cd "${PORTAGE_PYM_PATH}" ; ${cat_cmd} "${PORTAGE_LOG_FILE}" | \
+			"${PORTAGE_PYTHON:-/usr/bin/python}" "${PORTAGE_BIN_PATH}"/check-implicit-pointer-usage.py || die "check-implicit-pointer-usage.py failed")
+
+		if [[ -n ${f} ]] ; then
 			# In the future this will be a forced "die". In preparation,
 			# increase the log level from "qa" to "eerror" so that people
-			# are aware this is a problem that must be fixed asap.
+			# are aware this is a problem that must be fixed ASAP.
 
-			# just warn on 32bit hosts but bail on 64bit hosts
+			# Just warn on 32bit hosts but bail on 64bit hosts
 			case ${CHOST} in
-				alpha*|hppa64*|ia64*|powerpc64*|mips64*|sparc64*|sparcv9*|x86_64*) gentoo_bug=yes ;;
+				alpha*|aarch64*|arm64*|hppa64*|ia64*|powerpc64*|loongarch64*|mips64*|riscv64*|sparc64*|sparcv9*|s390x*|x86_64*) gentoo_bug=yes ;;
 			esac
 
 			abort=yes
 
-			if [[ $gentoo_bug = yes ]] ; then
+			if [[ ${gentoo_bug} = yes ]] ; then
 				eerror
 				eerror "QA Notice: Package triggers severe warnings which indicate that it"
 				eerror "           will almost certainly crash on 64bit architectures."
