Merge branch 'master' of git+ssh://git.overlays.gentoo.org/proj/portage into public_api

diff --git a/bin/ebuild-helpers/dobin b/bin/ebuild-helpers/dobin
--- a/bin/ebuild-helpers/dobin
+++ b/bin/ebuild-helpers/dobin
@@ -1,19 +1,20 @@
 #!/bin/bash
-# Copyright 1999-2011 Gentoo Foundation
+# Copyright 1999-2012 Gentoo Foundation
 # Distributed under the terms of the GNU General Public License v2
 
 source "${PORTAGE_BIN_PATH:-/usr/lib/portage/bin}"/isolated-functions.sh
 
 if [[ $# -lt 1 ]] ; then
-	helpers_die "${0##*/}: at least one argument needed"
+	__helpers_die "${0##*/}: at least one argument needed"
 	exit 1
 fi
 
-[[ " ${FEATURES} " == *" force-prefix "* ]] || \
-	case "$EAPI" in 0|1|2) ED=${D} ;; esac
+if ! ___eapi_has_prefix_variables; then
+	ED=${D}
+fi
 
 if [[ ! -d ${ED}${DESTTREE}/bin ]] ; then
-	install -d "${ED}${DESTTREE}/bin" || { helpers_die "${0##*/}: failed to install ${ED}${DESTTREE}/bin"; exit 2; }
+	install -d "${ED}${DESTTREE}/bin" || { __helpers_die "${0##*/}: failed to install ${ED}${DESTTREE}/bin"; exit 2; }
 fi
 
 ret=0
@@ -28,5 +29,5 @@ for x in "$@" ; do
 	((ret|=$?))
 done
 
-[[ $ret -ne 0 ]] && helpers_die "${0##*/} failed"
+[[ $ret -ne 0 ]] && __helpers_die "${0##*/} failed"
 exit ${ret}
diff --git a/bin/ebuild-helpers/dodoc b/bin/ebuild-helpers/dodoc
--- a/bin/ebuild-helpers/dodoc
+++ b/bin/ebuild-helpers/dodoc
@@ -1,16 +1,24 @@
 #!/bin/bash
-# Copyright 1999-2011 Gentoo Foundation
+# Copyright 1999-2012 Gentoo Foundation
 # Distributed under the terms of the GNU General Public License v2
 
 source "${PORTAGE_BIN_PATH:-/usr/lib/portage/bin}"/isolated-functions.sh
 
-if [ $# -lt 1 ] ; then
-	helpers_die "${0##*/}: at least one argument needed"
-	exit 1 	
+if ___eapi_dodoc_supports_-r; then
+	exec \
+	env \
+	__PORTAGE_HELPER="dodoc" \
+	doins "$@"
 fi
 
-[[ " ${FEATURES} " == *" force-prefix "* ]] || \
-	case "$EAPI" in 0|1|2) ED=${D} ;; esac
+if [ $# -lt 1 ] ; then
+	__helpers_die "${0##*/}: at least one argument needed"
+	exit 1
+fi
+
+if ! ___eapi_has_prefix_variables; then
+	ED=${D}
+fi
 
 dir="${ED}usr/share/doc/${PF}/${_E_DOCDESTTREE_}"
 if [ ! -d "${dir}" ] ; then
@@ -30,5 +38,5 @@ for x in "$@" ; do
 	fi
 done
 
-[[ $ret -ne 0 ]] && helpers_die "${0##*/} failed"
+[[ $ret -ne 0 ]] && __helpers_die "${0##*/} failed"
 exit ${ret}
diff --git a/bin/ebuild-helpers/doexe b/bin/ebuild-helpers/doexe
--- a/bin/ebuild-helpers/doexe
+++ b/bin/ebuild-helpers/doexe
@@ -1,23 +1,23 @@
 #!/bin/bash
-# Copyright 1999-2011 Gentoo Foundation
+# Copyright 1999-2012 Gentoo Foundation
 # Distributed under the terms of the GNU General Public License v2
 
 source "${PORTAGE_BIN_PATH:-/usr/lib/portage/bin}"/isolated-functions.sh
 
 if [[ $# -lt 1 ]] ; then
-	helpers_die "${0##*/}: at least one argument needed"
+	__helpers_die "${0##*/}: at least one argument needed"
 	exit 1
 fi
 
-[[ " ${FEATURES} " == *" force-prefix "* ]] || \
-	case "$EAPI" in 0|1|2) ED=${D} ;; esac
+if ! ___eapi_has_prefix_variables; then
+	ED=${D}
+fi
 
 if [[ ! -d ${ED}${_E_EXEDESTTREE_} ]] ; then
 	install -d "${ED}${_E_EXEDESTTREE_}"
 fi
 
-TMP=$T/.doexe_tmp
-mkdir "$TMP"
+TMP=$(mktemp -d "${T}/.doexe_tmp_XXXXXX")
 
 ret=0
 
@@ -26,7 +26,7 @@ for x in "$@" ; do
 		cp "$x" "$TMP"
 		mysrc=$TMP/${x##*/}
 	elif [ -d "${x}" ] ; then
-		vecho "doexe: warning, skipping directory ${x}"
+		__vecho "doexe: warning, skipping directory ${x}"
 		continue
 	else
 		mysrc="${x}"
@@ -42,5 +42,5 @@ done
 
 rm -rf "$TMP"
 
-[[ $ret -ne 0 ]] && helpers_die "${0##*/} failed"
+[[ $ret -ne 0 ]] && __helpers_die "${0##*/} failed"
 exit $ret
diff --git a/bin/ebuild-helpers/doinfo b/bin/ebuild-helpers/doinfo
--- a/bin/ebuild-helpers/doinfo
+++ b/bin/ebuild-helpers/doinfo
@@ -1,19 +1,20 @@
 #!/bin/bash
-# Copyright 1999-2011 Gentoo Foundation
+# Copyright 1999-2012 Gentoo Foundation
 # Distributed under the terms of the GNU General Public License v2
 
 source "${PORTAGE_BIN_PATH:-/usr/lib/portage/bin}"/isolated-functions.sh
 
 if [[ -z $1 ]] ; then
-	helpers_die "${0##*/}: at least one argument needed"
-	exit 1 	
+	__helpers_die "${0##*/}: at least one argument needed"
+	exit 1
 fi
 
-[[ " ${FEATURES} " == *" force-prefix "* ]] || \
-	case "$EAPI" in 0|1|2) ED=${D} ;; esac
+if ! ___eapi_has_prefix_variables; then
+	ED=${D}
+fi
 
 if [[ ! -d ${ED}usr/share/info ]] ; then
-	install -d "${ED}usr/share/info" || { helpers_die "${0##*/}: failed to install ${ED}usr/share/info"; exit 1; }
+	install -d "${ED}usr/share/info" || { __helpers_die "${0##*/}: failed to install ${ED}usr/share/info"; exit 1; }
 fi
 
 install -m0644 "$@" "${ED}usr/share/info"
@@ -22,6 +23,6 @@ if [ $rval -ne 0 ] ; then
 	for x in "$@" ; do
 		[ -e "$x" ] || echo "!!! ${0##*/}: $x does not exist" 1>&2
 	done
-	helpers_die "${0##*/} failed"
+	__helpers_die "${0##*/} failed"
 fi
 exit $rval
diff --git a/bin/ebuild-helpers/dolib b/bin/ebuild-helpers/dolib
--- a/bin/ebuild-helpers/dolib
+++ b/bin/ebuild-helpers/dolib
@@ -1,11 +1,12 @@
 #!/bin/bash
-# Copyright 1999-2011 Gentoo Foundation
+# Copyright 1999-2012 Gentoo Foundation
 # Distributed under the terms of the GNU General Public License v2
 
 source "${PORTAGE_BIN_PATH:-/usr/lib/portage/bin}"/isolated-functions.sh
 
-[[ " ${FEATURES} " == *" force-prefix "* ]] || \
-	case "$EAPI" in 0|1|2) ED=${D} ;; esac
+if ! ___eapi_has_prefix_variables; then
+	ED=${D}
+fi
 
 # Setup ABI cruft
 LIBDIR_VAR="LIBDIR_${ABI}"
@@ -19,11 +20,11 @@ libdir="${ED}${DESTTREE}/${CONF_LIBDIR}"
 
 
 if [[ $# -lt 1 ]] ; then
-	helpers_die "${0##*/}: at least one argument needed"
+	__helpers_die "${0##*/}: at least one argument needed"
 	exit 1
 fi
 if [[ ! -d ${libdir} ]] ; then
-	install -d "${libdir}" || { helpers_die "${0##*/}: failed to install ${libdir}"; exit 1; }
+	install -d "${libdir}" || { __helpers_die "${0##*/}: failed to install ${libdir}"; exit 1; }
 fi
 
 ret=0
@@ -42,5 +43,5 @@ for x in "$@" ; do
 	((ret|=$?))
 done
 
-[[ $ret -ne 0 ]] && helpers_die "${0##*/} failed"
+[[ $ret -ne 0 ]] && __helpers_die "${0##*/} failed"
 exit ${ret}
diff --git a/bin/ebuild-helpers/domo b/bin/ebuild-helpers/domo
--- a/bin/ebuild-helpers/domo
+++ b/bin/ebuild-helpers/domo
@@ -1,17 +1,18 @@
 #!/bin/bash
-# Copyright 1999-2011 Gentoo Foundation
+# Copyright 1999-2012 Gentoo Foundation
 # Distributed under the terms of the GNU General Public License v2
 
 source "${PORTAGE_BIN_PATH:-/usr/lib/portage/bin}"/isolated-functions.sh
 
 mynum=${#}
 if [ ${mynum} -lt 1 ] ; then
-	helpers_die "${0}: at least one argument needed"
+	__helpers_die "${0}: at least one argument needed"
 	exit 1
 fi
 
-[[ " ${FEATURES} " == *" force-prefix "* ]] || \
-	case "$EAPI" in 0|1|2) ED=${D} ;; esac
+if ! ___eapi_has_prefix_variables; then
+	ED=${D}
+fi
 
 if [ ! -d "${ED}${DESTTREE}/share/locale" ] ; then
 	install -d "${ED}${DESTTREE}/share/locale/"
@@ -34,5 +35,5 @@ for x in "$@" ; do
 	((ret|=$?))
 done
 
-[[ $ret -ne 0 ]] && helpers_die "${0##*/} failed"
+[[ $ret -ne 0 ]] && __helpers_die "${0##*/} failed"
 exit $ret
diff --git a/bin/ebuild-helpers/dosym b/bin/ebuild-helpers/dosym
--- a/bin/ebuild-helpers/dosym
+++ b/bin/ebuild-helpers/dosym
@@ -5,12 +5,13 @@
 source "${PORTAGE_BIN_PATH:-/usr/lib/portage/bin}"/isolated-functions.sh
 
 if [[ $# -ne 2 ]] ; then
-	helpers_die "${0##*/}: two arguments needed"
+	__helpers_die "${0##*/}: two arguments needed"
 	exit 1
 fi
 
-[[ " ${FEATURES} " == *" force-prefix "* ]] || \
-	case "$EAPI" in 0|1|2) ED=${D} ;; esac
+if ! ___eapi_has_prefix_variables; then
+	ED=${D}
+fi
 
 if [[ ${2} == */ ]] || \
 	[[ -d ${ED}${2} && ! -L ${ED}${2} ]] ; then
@@ -26,5 +27,5 @@ target="${1}"
 ln -snf "${target}" "${ED}${2}"
 
 ret=$?
-[[ $ret -ne 0 ]] && helpers_die "${0##*/} failed"
+[[ $ret -ne 0 ]] && __helpers_die "${0##*/} failed"
 exit $ret
diff --git a/bin/ebuild-helpers/ecompressdir b/bin/ebuild-helpers/ecompressdir
--- a/bin/ebuild-helpers/ecompressdir
+++ b/bin/ebuild-helpers/ecompressdir
@@ -1,18 +1,21 @@
 #!/bin/bash
-# Copyright 1999-2011 Gentoo Foundation
+# Copyright 1999-2013 Gentoo Foundation
 # Distributed under the terms of the GNU General Public License v2
 
 source "${PORTAGE_BIN_PATH:-/usr/lib/portage/bin}"/helper-functions.sh
 
 if [[ -z $1 ]] ; then
-	helpers_die "${0##*/}: at least one argument needed"
+	__helpers_die "${0##*/}: at least one argument needed"
 	exit 1
 fi
 
-[[ " ${FEATURES} " == *" force-prefix "* ]] || \
-	case "$EAPI" in 0|1|2) ED=${D} EPREFIX= ;; esac
+if ! ___eapi_has_prefix_variables; then
+	ED=${D} EPREFIX=
+fi
 
-case $1 in
+SIZE_LIMIT=''
+while [[ $# -gt 0 ]] ; do
+	case $1 in
 	--ignore)
 		shift
 		for skip in "$@" ; do
@@ -27,45 +30,66 @@ case $1 in
 		set -- "${@/#/${ED}}"
 		ret=0
 		for x in "$@" ; do
-			>> "$x"
+			# Stash the limit in the .dir file so we can reload it later.
+			printf "${SIZE_LIMIT}" > "${x}"
 			((ret|=$?))
 		done
-		[[ $ret -ne 0 ]] && helpers_die "${0##*/} failed"
+		[[ $ret -ne 0 ]] && __helpers_die "${0##*/} failed"
 		exit $ret
 		;;
 	--dequeue)
-		[[ -n $2 ]] && vecho "${0##*/}: --dequeue takes no additional arguments" 1>&2
+		[[ -n $2 ]] && __vecho "${0##*/}: --dequeue takes no additional arguments" 1>&2
 		find "${ED}" -name '*.ecompress.dir' -print0 \
 			| sed -e 's:\.ecompress\.dir::g' -e "s:${ED}:/:g" \
 			| ${XARGS} -0 ecompressdir
 		find "${ED}" -name '*.ecompress.skip' -print0 | ${XARGS} -0 rm -f
 		exit 0
 		;;
+	--limit)
+		SIZE_LIMIT=$2
+		shift
+		;;
 	--*)
-		helpers_die "${0##*/}: unknown arguments '$*'"
+		__helpers_die "${0##*/}: unknown arguments '$*'"
 		exit 1
 		;;
-esac
+	*)
+		break
+		;;
+	esac
+	shift
+done
 
 # figure out the new suffix
 suffix=$(ecompress --suffix)
 
-# funk_up_dir(action, suffix, binary)
+# funk_up_dir(action, suffix, binary, [size_limit])
 #	- action: compress or decompress
 #	- suffix: the compression suffix to work with
 #	- binary: the program to execute that'll compress/decompress
+#   - size_limit: if compressing, skip files smaller than this
 # The directory we act on is implied in the ${dir} variable
 funk_up_dir() {
-	local act=$1 suffix=$2 binary=$3
+	local act=$1 suffix=$2 binary=$3 size_limit=$4
 
 	local negate=""
 	[[ ${act} == "compress" ]] && negate="!"
 
 	local ret=0
 	# first we act on all the files
-	find "${dir}" -type f ${negate} -iname '*'${suffix} -print0 | ${XARGS} -0 ${binary}
+	local args=(
+		-type f
+		${negate} -iname "*${suffix}"
+	)
+	[[ -n ${size_limit} ]] && args+=( -size "+${size_limit}c" )
+	find "${dir}" "${args[@]}" -print0 | ${XARGS} -0 ${binary}
 	((ret|=$?))
 
+	# Repeat until nothing changes, in order to handle multiple
+	# levels of indirection (see bug #470916).
+	local -i indirection=0
+	while true ; do
+	local something_changed=
 	while read -r -d $'\0' brokenlink ; do
 		[[ -e ${brokenlink} ]] && continue
 		olddest=$(readlink "${brokenlink}")
@@ -91,12 +115,22 @@ funk_up_dir() {
 		else
 			[[ -f "${dir}/${brokenlink%/*}/${newdest}" ]] || continue
 		fi
+		something_changed=${brokenlink}
 		rm -f "${brokenlink}"
 		[[ ${act} == "compress" ]] \
 			&& ln -snf "${newdest}" "${brokenlink}${suffix}" \
 			|| ln -snf "${newdest}" "${brokenlink%${suffix}}"
 		((ret|=$?))
 	done < <(find "${dir}" -type l -print0)
+	[[ -n ${something_changed} ]] || break
+	(( indirection++ ))
+	if (( indirection >= 100 )) ; then
+		# Protect against possibility of a bug triggering an endless loop.
+		eerror "ecompressdir: too many levels of indirection for" \
+			"'${actual_dir#${ED}}/${something_changed#./}'"
+		break
+	fi
+	done
 	return ${ret}
 }
 
@@ -133,13 +167,13 @@ decompressors=(
 	".lzma" "unxz -f"
 )
 
-multijob_init
+__multijob_init
 
 for dir in "$@" ; do
 	dir=${dir#/}
 	dir="${ED}${dir}"
 	if [[ ! -d ${dir} ]] ; then
-		vecho "${0##*/}: /${dir#${ED}} does not exist!"
+		__vecho "${0##*/}: /${dir#${ED}} does not exist!"
 		continue
 	fi
 	cd "${dir}"
@@ -151,24 +185,25 @@ for dir in "$@" ; do
 
 	# since we've been requested to compress the whole dir,
 	# delete any individual queued requests
+	size_limit=${SIZE_LIMIT:-$(<"${actual_dir}.ecompress.dir")}
 	rm -f "${actual_dir}.ecompress.dir"
 	find "${dir}" -type f -name '*.ecompress.file' -print0 | ${XARGS} -0 rm -f
 
 	# not uncommon for packages to compress doc files themselves
-	for (( d = 0; d < ${#decompressors[@]}; d += 2 )) ; do
+	for (( i = 0; i < ${#decompressors[@]}; i += 2 )) ; do
 		# It's faster to parallelize at this stage than to try to
 		# parallelize the compressors.  This is because the find|xargs
 		# ends up launching less compressors overall, so the overhead
 		# of forking children ends up dominating.
 		(
-		multijob_child_init
+		__multijob_child_init
 		funk_up_dir "decompress" "${decompressors[i]}" "${decompressors[i+1]}"
 		) &
-		multijob_post_fork
+		__multijob_post_fork
 		: $(( ret |= $? ))
 	done
 
-	multijob_finish
+	__multijob_finish
 	: $(( ret |= $? ))
 
 	# forcibly break all hard links as some compressors whine about it
@@ -177,8 +212,8 @@ for dir in "$@" ; do
 
 	# now lets do our work
 	if [[ -n ${suffix} ]] ; then
-		vecho "${0##*/}: $(ecompress --bin) /${actual_dir#${ED}}"
-		funk_up_dir "compress" "${suffix}" "ecompress"
+		__vecho "${0##*/}: $(ecompress --bin) /${actual_dir#${ED}}"
+		funk_up_dir "compress" "${suffix}" "ecompress" "${size_limit}"
 		: $(( ret |= $? ))
 	fi
 
@@ -186,5 +221,5 @@ for dir in "$@" ; do
 	restore_skip_dirs
 done
 
-[[ $ret -ne 0 ]] && helpers_die "${0##*/} failed"
+[[ $ret -ne 0 ]] && __helpers_die "${0##*/} failed"
 exit ${ret}
diff --git a/bin/ebuild-helpers/fowners b/bin/ebuild-helpers/fowners
--- a/bin/ebuild-helpers/fowners
+++ b/bin/ebuild-helpers/fowners
@@ -4,8 +4,9 @@
 
 source "${PORTAGE_BIN_PATH:-/usr/lib/portage/bin}"/isolated-functions.sh
 
-[[ " ${FEATURES} " == *" force-prefix "* ]] || \
-	case "$EAPI" in 0|1|2) EPREFIX= ED=${D} ;; esac
+if ! ___eapi_has_prefix_variables; then
+	EPREFIX= ED=${D}
+fi
 
 # we can't prefix all arguments because
 # chown takes random options
@@ -13,10 +14,5 @@ slash="/"
 chown "${@/#${slash}/${ED}${slash}}"
 ret=$?
 
-if [[ ${ret} != 0 && -n ${EPREFIX} && ${EUID} != 0 ]] ; then
-	ewarn "fowners failure ignored in Prefix with non-privileged user"
-	exit 0
-fi
-
-[[ $ret -ne 0 ]] && helpers_die "${0##*/} failed"
+[[ $ret -ne 0 ]] && __helpers_die "${0##*/} failed"
 exit $ret
diff --git a/bin/ebuild-helpers/newins b/bin/ebuild-helpers/newins
--- a/bin/ebuild-helpers/newins
+++ b/bin/ebuild-helpers/newins
@@ -1,38 +1,57 @@
 #!/bin/bash
-# Copyright 1999-2011 Gentoo Foundation
+# Copyright 1999-2012 Gentoo Foundation
 # Distributed under the terms of the GNU General Public License v2
 
 source "${PORTAGE_BIN_PATH:-/usr/lib/portage/bin}"/isolated-functions.sh
 
-if [[ -z ${T} ]] || [[ -z ${2} ]] ; then
-	helpers_die "${0##*/}: Need two arguments, old file and new file"
-	exit 1
-fi
+helper=${0##*/}
 
-if [ ! -e "$1" ] ; then
-	helpers_die "!!! ${0##*/}: $1 does not exist"
+if [[ -z ${T} ]] || [[ -z ${2} ]] ; then
+	__helpers_die "${helper}: Need two arguments, old file and new file"
 	exit 1
 fi
 
 (($#>2)) && \
-	eqawarn "QA Notice: ${0##*/} called with more than 2 arguments: ${@:3}"
+	eqawarn "QA Notice: ${helper} called with more than 2 arguments: ${@:3}"
 
-rm -rf "${T}/${2}" || exit $?
-case "$EAPI" in
-	0|1|2|3|3_pre2)
-		cp "$1" "$T/$2" || exit $?
-		;;
-	*)
-		cp -P "$1" "$T/$2"
-		ret=$?
-		if [[ $ret -ne 0 ]] ; then
-			helpers_die "${0##*/} failed"
-			exit $ret
+stdin=
+if ___eapi_newins_supports_reading_from_standard_input && [[ $1 == "-" ]]; then
+	stdin=yes
+fi
+
+TMP=$(mktemp -d "${T}/.newins_tmp_XXXXXX")
+trap 'rm -rf "${TMP}"' EXIT
+
+if [[ ${stdin} ]] ; then
+	if [[ -t 0 ]] ; then
+		__helpers_die "!!! ${helper}: Input is from a terminal"
+		exit 1
+	fi
+	cat > "${TMP}/$2"
+	ret=$?
+else
+	if [[ ! -e $1 ]] ; then
+		__helpers_die "!!! ${helper}: $1 does not exist"
+		exit 1
+	fi
+
+	cp_args="-f"
+	if [[ ${helper} == newins ]] ; then
+		if ___eapi_doins_and_newins_preserve_symlinks; then
+			cp_args+=" -P"
 		fi
-		;;
-esac
-doins "${T}/${2}"
+	fi
+
+	cp ${cp_args} "$1" "${TMP}/$2"
+	ret=$?
+fi
+
+if [[ ${ret} -ne 0 ]] ; then
+	__helpers_die "${0##*/} failed"
+	exit ${ret}
+fi
+
+do${helper#new} "${TMP}/$2"
 ret=$?
-rm -rf "${T}/${2}"
-[[ $ret -ne 0 ]] && helpers_die "${0##*/} failed"
+[[ $ret -ne 0 ]] && __helpers_die "${helper} failed"
 exit $ret
diff --git a/bin/ebuild-helpers/prepstrip b/bin/ebuild-helpers/prepstrip
--- a/bin/ebuild-helpers/prepstrip
+++ b/bin/ebuild-helpers/prepstrip
@@ -1,7 +1,8 @@
 #!/bin/bash
-# Copyright 1999-2012 Gentoo Foundation
+# Copyright 1999-2014 Gentoo Foundation
 # Distributed under the terms of the GNU General Public License v2
 
+PORTAGE_PYM_PATH=${PORTAGE_PYM_PATH:-/usr/lib/portage/pym}
 source "${PORTAGE_BIN_PATH:-/usr/lib/portage/bin}"/helper-functions.sh
 
 # avoid multiple calls to `has`.  this creates things like:
@@ -15,11 +16,12 @@ exp_tf() {
 		eval ${var}_${flag}=$(tf has ${flag} ${!var})
 	done
 }
-exp_tf FEATURES compressdebug installsources nostrip splitdebug
-exp_tf RESTRICT binchecks installsources strip
+exp_tf FEATURES compressdebug installsources nostrip splitdebug xattr
+exp_tf RESTRICT binchecks installsources splitdebug strip
 
-[[ " ${FEATURES} " == *" force-prefix "* ]] || \
-	case "${EAPI}" in 0|1|2) EPREFIX= ED=${D} ;; esac
+if ! ___eapi_has_prefix_variables; then
+	EPREFIX= ED=${D}
+fi
 
 banner=false
 SKIP_STRIP=false
@@ -27,6 +29,30 @@ if ${RESTRICT_strip} || ${FEATURES_nostrip} ; then
 	SKIP_STRIP=true
 	banner=true
 	${FEATURES_installsources} || exit 0
+fi
+
+PRESERVE_XATTR=false
+if [[ ${KERNEL} == linux ]] && ${FEATURES_xattr} ; then
+	PRESERVE_XATTR=true
+	if type -P getfattr >/dev/null && type -P setfattr >/dev/null ; then
+		dump_xattrs() {
+			getfattr -d --absolute-names "$1"
+		}
+		restore_xattrs() {
+			setfattr --restore=-
+		}
+	else
+		dump_xattrs() {
+			PYTHONPATH=${PORTAGE_PYTHONPATH:-${PORTAGE_PYM_PATH}} \
+			"${PORTAGE_PYTHON:-/usr/bin/python}" \
+			"${PORTAGE_BIN_PATH}/xattr-helper.py" --dump < <(echo -n "$1")
+		}
+		restore_xattrs() {
+			PYTHONPATH=${PORTAGE_PYTHONPATH:-${PORTAGE_PYM_PATH}} \
+			"${PORTAGE_PYTHON:-/usr/bin/python}" \
+			"${PORTAGE_BIN_PATH}/xattr-helper.py" --restore
+		}
+	fi
 fi
 
 # look up the tools we might be using
@@ -51,7 +77,7 @@ case $(${STRIP} --version 2>/dev/null) in
 	# We'll leave out -R .note for now until we can check out the relevance
 	# of the section when it has the ALLOC flag set on it ...
 	SAFE_STRIP_FLAGS="--strip-unneeded"
-	DEF_STRIP_FLAGS="-R .comment -R .GCC.command.line"
+	DEF_STRIP_FLAGS="-R .comment -R .GCC.command.line -R .note.gnu.gold-version"
 	SPLIT_STRIP_FLAGS=
 	;;
 esac
@@ -62,22 +88,12 @@ prepstrip_sources_dir=${EPREFIX}/usr/src/debug/${CATEGORY}/${PF}
 type -P debugedit >/dev/null && debugedit_found=true || debugedit_found=false
 debugedit_warned=false
 
-multijob_init
+__multijob_init
 
 # Setup $T filesystem layout that we care about.
 tmpdir="${T}/prepstrip"
 rm -rf "${tmpdir}"
 mkdir -p "${tmpdir}"/{inodes,splitdebug,sources}
-
-# Usage: inode_var_name: <file>
-inode_file_link() {
-	echo -n "${tmpdir}/inodes/"
-	if  [[ ${USERLAND} == "BSD" ]] ; then
-		stat -f '%i' "$1"
-	else
-		stat -c '%i' "$1"
-	fi
-}
 
 # Usage: save_elf_sources <elf>
 save_elf_sources() {
@@ -93,7 +109,6 @@ save_elf_sources() {
 	fi
 
 	local x=$1
-	[[ -f $(inode_file_link "${x}") ]] && return 0
 
 	# since we're editing the ELF here, we should recompute the build-id
 	# (the -i flag below).  save that output so we don't need to recompute
@@ -101,20 +116,22 @@ save_elf_sources() {
 	buildid=$(debugedit -i \
 		-b "${WORKDIR}" \
 		-d "${prepstrip_sources_dir}" \
-		-l "${tmpdir}/sources/${x##*/}.${BASHPID}" \
+		-l "${tmpdir}/sources/${x##*/}.${BASHPID:-$(__bashpid)}" \
 		"${x}")
 }
 
 # Usage: save_elf_debug <elf> [splitdebug file]
 save_elf_debug() {
 	${FEATURES_splitdebug} || return 0
+	${RESTRICT_splitdebug} && return 0
 
 	# NOTE: Debug files must be installed in
 	# ${EPREFIX}/usr/lib/debug/${EPREFIX} (note that ${EPREFIX} occurs
 	# twice in this path) in order for gdb's debug-file-directory
 	# lookup to work correctly.
 	local x=$1
-	local splitdebug=$2
+	local inode_debug=$2
+	local splitdebug=$3
 	local y=${ED}usr/lib/debug/${x:${#D}}.debug
 
 	# dont save debug info twice
@@ -122,9 +139,8 @@ save_elf_debug() {
 
 	mkdir -p "${y%/*}"
 
-	local inode=$(inode_file_link "${x}")
-	if [[ -f ${inode} ]] ; then
-		ln "${inode}" "${y}"
+	if [ -f "${inode_debug}" ] ; then
+		ln "${inode_debug}" "${y}" || die "ln failed unexpectedly"
 	else
 		if [[ -n ${splitdebug} ]] ; then
 			mv "${splitdebug}" "${y}"
@@ -134,64 +150,89 @@ save_elf_debug() {
 			${OBJCOPY} ${objcopy_flags} "${x}" "${y}"
 			${OBJCOPY} --add-gnu-debuglink="${y}" "${x}"
 		fi
-		local args="a-x,o-w"
-		[[ -g ${x} || -u ${x} ]] && args+=",go-r"
-		chmod ${args} "${y}"
-		ln "${y}" "${inode}"
+		# Only do the following if the debug file was
+		# successfully created (see bug #446774).
+		if [ $? -eq 0 ] ; then
+			local args="a-x,o-w"
+			[[ -g ${x} || -u ${x} ]] && args+=",go-r"
+			chmod ${args} "${y}"
+			ln "${y}" "${inode_debug}" || die "ln failed unexpectedly"
+		fi
 	fi
 
 	# if we don't already have build-id from debugedit, look it up
 	if [[ -z ${buildid} ]] ; then
 		# convert the readelf output to something useful
-		buildid=$(${READELF} -x .note.gnu.build-id "${x}" 2>/dev/null \
-			| awk '$NF ~ /GNU/ { getline; printf $2$3$4$5; getline; print $2 }')
+		buildid=$(${READELF} -n "${x}" 2>/dev/null | awk '/Build ID:/{ print $NF; exit }')
 	fi
 	if [[ -n ${buildid} ]] ; then
 		local buildid_dir="${ED}usr/lib/debug/.build-id/${buildid:0:2}"
 		local buildid_file="${buildid_dir}/${buildid:2}"
 		mkdir -p "${buildid_dir}"
-		ln -s "../../${x:${#D}}.debug" "${buildid_file}.debug"
-		ln -s "/${x:${#D}}" "${buildid_file}"
+		[ -L "${buildid_file}".debug ] || ln -s "../../${x:${#D}}.debug" "${buildid_file}.debug"
+		[ -L "${buildid_file}" ] || ln -s "/${x:${#D}}" "${buildid_file}"
 	fi
 }
 
 # Usage: process_elf <elf>
 process_elf() {
-	local x=$1 strip_flags=${*:2}
+	local x=$1 inode_link=$2 strip_flags=${*:3}
+	local already_stripped lockfile xt_data
 
-	vecho "   ${x:${#ED}}"
-	save_elf_sources "${x}"
+	__vecho "   ${x:${#ED}}"
+
+	# If two processes try to debugedit or strip the same hardlink at the
+	# same time, it may corrupt files or cause loss of splitdebug info.
+	# So, use a lockfile to prevent interference (easily observed with
+	# dev-vcs/git which creates ~111 hardlinks to one file in
+	# /usr/libexec/git-core).
+	lockfile=${inode_link}_lockfile
+	if ! ln "${inode_link}" "${lockfile}" 2>/dev/null ; then
+		while [[ -f ${lockfile} ]] ; do
+			sleep 1
+		done
+		unset lockfile
+	fi
+
+	[ -f "${inode_link}_stripped" ] && already_stripped=true || already_stripped=false
+
+	if ! ${already_stripped} ; then
+		if ${PRESERVE_XATTR} ; then
+			xt_data=$(dump_xattrs "${x}")
+		fi
+		save_elf_sources "${x}"
+	fi
 
 	if ${strip_this} ; then
-
-		# If two processes try to strip the same hardlink at the same
-		# time, it will cause one of them to lose the splitdebug info.
-		# So, use a lockfile to prevent interference (easily observed
-		# with dev-vcs/git which creates ~109 hardlinks to one file in
-		# /usr/libexec/git-core).
-		local lockfile=$(inode_file_link "${x}")_lockfile
-		if ! ln "${x}" "${lockfile}" ; then
-			while [[ -f ${lockfile} ]] ; do
-				sleep 1
-			done
-			unset lockfile
-		fi
 
 		# see if we can split & strip at the same time
 		if [[ -n ${SPLIT_STRIP_FLAGS} ]] ; then
 			local shortname="${x##*/}.debug"
-			local splitdebug="${tmpdir}/splitdebug/${shortname}.${BASHPID}"
+			local splitdebug="${tmpdir}/splitdebug/${shortname}.${BASHPID:-$(__bashpid)}"
+			${already_stripped} || \
 			${STRIP} ${strip_flags} \
 				-f "${splitdebug}" \
 				-F "${shortname}" \
 				"${x}"
-			save_elf_debug "${x}" "${splitdebug}"
+			save_elf_debug "${x}" "${inode_link}_debug" "${splitdebug}"
 		else
-			save_elf_debug "${x}"
+			save_elf_debug "${x}" "${inode_link}_debug"
+			${already_stripped} || \
 			${STRIP} ${strip_flags} "${x}"
 		fi
-		[[ -n ${lockfile} ]] && rm -f "${lockfile}"
 	fi
+
+	if ${already_stripped} ; then
+		rm -f "${x}" || die "rm failed unexpectedly"
+		ln "${inode_link}_stripped" "${x}" || die "ln failed unexpectedly"
+	else
+		ln "${x}" "${inode_link}_stripped" || die "ln failed unexpectedly"
+		if [[ ${xt_data} ]] ; then
+			restore_xattrs <<< "${xt_data}"
+		fi
+	fi
+
+	[[ -n ${lockfile} ]] && rm -f "${lockfile}"
 }
 
 # The existance of the section .symtab tells us that a binary is stripped.
@@ -204,7 +245,7 @@ if ! ${RESTRICT_binchecks} && ! ${RESTRICT_strip} ; then
 	log=${tmpdir}/scanelf-already-stripped.log
 	scanelf -yqRBF '#k%F' -k '!.symtab' "$@" | sed -e "s#^${ED}##" > "${log}"
 	(
-	multijob_child_init
+	__multijob_child_init
 	qa_var="QA_PRESTRIPPED_${ARCH/-/_}"
 	[[ -n ${!qa_var} ]] && QA_PRESTRIPPED="${!qa_var}"
 	if [[ -n ${QA_PRESTRIPPED} && -s ${log} && \
@@ -219,28 +260,49 @@ if ! ${RESTRICT_binchecks} && ! ${RESTRICT_strip} ; then
 	fi
 	sed -e "/^\$/d" -e "s#^#/#" -i "${log}"
 	if [[ -s ${log} ]] ; then
-		vecho -e "\n"
+		__vecho -e "\n"
 		eqawarn "QA Notice: Pre-stripped files found:"
 		eqawarn "$(<"${log}")"
 	else
 		rm -f "${log}"
 	fi
 	) &
-	multijob_post_fork
+	__multijob_post_fork
 fi
 
+# Since strip creates a new inode, we need to know the initial set of
+# inodes in advance, so that we can avoid interference due to trying
+# to strip the same (hardlinked) file multiple times in parallel.
+# See bug #421099.
+if  [[ ${USERLAND} == BSD ]] ; then
+	get_inode_number() { stat -f '%i' "$1"; }
+else
+	get_inode_number() { stat -c '%i' "$1"; }
+fi
+cd "${tmpdir}/inodes" || die "cd failed unexpectedly"
+while read -r x ; do
+	inode_link=$(get_inode_number "${x}") || die "stat failed unexpectedly"
+	echo "${x}" >> "${inode_link}" || die "echo failed unexpectedly"
+done < <(
+	# Use sort -u to eliminate duplicates for bug #445336.
+	(
+		scanelf -yqRBF '#k%F' -k '.symtab' "$@"
+		find "$@" -type f ! -type l -name '*.a'
+	) | LC_ALL=C sort -u
+)
+
 # Now we look for unstripped binaries.
-for x in \
-	$(scanelf -yqRBF '#k%F' -k '.symtab' "$@") \
-	$(find "$@" -type f -name '*.a')
+for inode_link in $(shopt -s nullglob; echo *) ; do
+while read -r x
 do
+
 	if ! ${banner} ; then
-		vecho "strip: ${STRIP} ${PORTAGE_STRIP_FLAGS}"
+		__vecho "strip: ${STRIP} ${PORTAGE_STRIP_FLAGS}"
 		banner=true
 	fi
 
 	(
-	multijob_child_init
+	__multijob_child_init
 	f=$(file "${x}") || exit 0
 	[[ -z ${f} ]] && exit 0
 
@@ -275,27 +337,34 @@ do
 
 	buildid=
 	if [[ ${f} == *"current ar archive"* ]] ; then
-		vecho "   ${x:${#ED}}"
+		__vecho "   ${x:${#ED}}"
 		if ${strip_this} ; then
-			# hmm, can we split debug/sources for .a ?
-			${STRIP} -g "${x}"
+			# If we have split debug enabled, then do not strip this.
+			# There is no concept of splitdebug for objects not yet
+			# linked in (only for finally linked ELFs), so we have to
+			# retain the debug info in the archive itself.
+			if ! ${FEATURES_splitdebug} || ${RESTRICT_splitdebug} ; then
+				${STRIP} -g "${x}"
+			fi
 		fi
 	elif [[ ${f} == *"SB executable"* || ${f} == *"SB shared object"* ]] ; then
-		process_elf "${x}" ${PORTAGE_STRIP_FLAGS}
+		process_elf "${x}" "${inode_link}" ${PORTAGE_STRIP_FLAGS}
 	elif [[ ${f} == *"SB relocatable"* ]] ; then
-		process_elf "${x}" ${SAFE_STRIP_FLAGS}
+		process_elf "${x}" "${inode_link}" ${SAFE_STRIP_FLAGS}
 	fi
 
 	if ${was_not_writable} ; then
 		chmod u-w "${x}"
 	fi
 	) &
-	multijob_post_fork
+	__multijob_post_fork
+
+done < "${inode_link}"
 done
 
 # With a bit more work, we could run the rsync processes below in
 # parallel, but not sure that'd be an overall improvement.
-multijob_finish
+__multijob_finish
 
 cd "${tmpdir}"/sources/ && cat * > "${tmpdir}/debug.sources" 2>/dev/null
 if [[ -s ${tmpdir}/debug.sources ]] && \
@@ -303,11 +372,11 @@ if [[ -s ${tmpdir}/debug.sources ]] && \
    ! ${RESTRICT_installsources} && \
    ${debugedit_found}
 then
-	vecho "installsources: rsyncing source files"
+	__vecho "installsources: rsyncing source files"
 	[[ -d ${D}${prepstrip_sources_dir} ]] || mkdir -p "${D}${prepstrip_sources_dir}"
 	grep -zv '/<[^/>]*>$' "${tmpdir}"/debug.sources | \
 		(cd "${WORKDIR}"; LANG=C sort -z -u | \
-		rsync -tL0 --files-from=- "${WORKDIR}/" "${D}${prepstrip_sources_dir}/" )
+		rsync -tL0 --chmod=ugo-st,a+r,go-w,Da+x,Fa-x --files-from=- "${WORKDIR}/" "${D}${prepstrip_sources_dir}/" )
 
 	# Preserve directory structure.
 	# Needed after running save_elf_sources.
diff --git a/bin/emerge-webrsync b/bin/emerge-webrsync
--- a/bin/emerge-webrsync
+++ b/bin/emerge-webrsync
@@ -1,5 +1,5 @@
 #!/bin/bash
-# Copyright 1999-2011 Gentoo Foundation
+# Copyright 1999-2014 Gentoo Foundation
 # Distributed under the terms of the GNU General Public License v2
 # Author: Karl Trygve Kalleberg <karltk@gentoo.org>
 # Rewritten from the old, Perl-based emerge-webrsync script
@@ -22,9 +22,9 @@ vvecho() { [[ ${do_verbose} -eq 1 ]] && echo "$@" ; }
 # Only echo if not in verbose mode
 nvecho() { [[ ${do_verbose} -eq 0 ]] && echo "$@" ; }
 # warning echos
-wecho() { echo "${argv0}: warning: $*" 1>&2 ; }
+wecho() { echo "${argv0##*/}: warning: $*" 1>&2 ; }
 # error echos
-eecho() { echo "${argv0}: error: $*" 1>&2 ; }
+eecho() { echo "${argv0##*/}: error: $*" 1>&2 ; }
 
 argv0=$0
 
@@ -39,12 +39,23 @@ else
 	eecho "could not find 'portageq'; aborting"
 	exit 1
 fi
-eval $("${portageq}" envvar -v FEATURES FETCHCOMMAND GENTOO_MIRRORS \
-	PORTAGE_BIN_PATH PORTAGE_GPG_DIR \
-	PORTAGE_NICENESS PORTAGE_RSYNC_EXTRA_OPTS PORTAGE_TMPDIR PORTDIR \
-	SYNC http_proxy ftp_proxy)
-DISTDIR="${PORTAGE_TMPDIR}/emerge-webrsync"
+eval "$("${portageq}" envvar -v DISTDIR EPREFIX FEATURES \
+	FETCHCOMMAND GENTOO_MIRRORS \
+	PORTAGE_BIN_PATH PORTAGE_CONFIGROOT PORTAGE_GPG_DIR \
+	PORTAGE_NICENESS PORTAGE_REPOSITORIES PORTAGE_RSYNC_EXTRA_OPTS \
+	PORTAGE_RSYNC_OPTS PORTAGE_TMPDIR \
+	USERLAND http_proxy ftp_proxy)"
 export http_proxy ftp_proxy
+
+source "${PORTAGE_BIN_PATH}"/isolated-functions.sh || exit 1
+
+repo_name=gentoo
+repo_location=$(__repo_attr "${repo_name}" location)
+if [[ -z ${repo_location} ]]; then
+	eecho "Repository '${repo_name}' not found"
+	exit 1
+fi
+repo_sync_type=$(__repo_attr "${repo_name}" sync-type)
 
 # If PORTAGE_NICENESS is overriden via the env then it will
 # still pass through the portageq call and override properly.
@@ -52,10 +63,9 @@ if [ -n "${PORTAGE_NICENESS}" ]; then
 	renice $PORTAGE_NICENESS $$ > /dev/null
 fi
 
-source "${PORTAGE_BIN_PATH}"/isolated-functions.sh || exit 1
-
 do_verbose=0
 do_debug=0
+keep=false
 
 if has webrsync-gpg ${FEATURES} ; then
 	WEBSYNC_VERIFY_SIGNATURE=1
@@ -99,7 +109,9 @@ get_date_part() {
 get_utc_second_from_string() {
 	local s="$1"
 	if [[ ${USERLAND} == BSD ]] ; then
-		date -juf "%Y%m%d" "$s" +"%s"
+		# Specify zeros for the least significant digits, or else those
+		# digits are inherited from the current system clock time.
+		date -juf "%Y%m%d%H%M.%S" "${s}0000.00" +"%s"
 	else
 		date -d "${s:0:4}-${s:4:2}-${s:6:2}" -u +"%s"
 	fi
@@ -108,8 +120,8 @@ get_utc_second_from_string() {
 get_portage_timestamp() {
 	local portage_current_timestamp=0
 
-	if [ -f "${PORTDIR}/metadata/timestamp.x" ]; then
-		portage_current_timestamp=$(cut -f 1 -d " " "${PORTDIR}/metadata/timestamp.x" )
+	if [ -f "${repo_location}/metadata/timestamp.x" ]; then
+		portage_current_timestamp=$(cut -f 1 -d " " "${repo_location}/metadata/timestamp.x" )
 	fi
 
 	echo "${portage_current_timestamp}"
@@ -125,13 +137,18 @@ fetch_file() {
 	elif [ "${FETCHCOMMAND/curl/}" != "${FETCHCOMMAND}" ]; then
 		opts="--continue-at - $(nvecho -s -f)"
 	else
-		rm -f "${FILE}"
+		rm -f "${DISTDIR}/${FILE}"
 	fi
 
-	vecho "Fetching file ${FILE} ..."
+	__vecho "Fetching file ${FILE} ..."
 	# already set DISTDIR=
-	eval "${FETCHCOMMAND}" ${opts}
-	[ -s "${FILE}" ]
+	eval "${FETCHCOMMAND} ${opts}"
+	if [[ $? -eq 0 && -s ${DISTDIR}/${FILE} ]] ; then
+		return 0
+	else
+		rm -f "${DISTDIR}/${FILE}"
+		return 1
+	fi
 }
 
 check_file_digest() {
@@ -139,10 +156,12 @@ check_file_digest() {
 	local file="$2"
 	local r=1
 
-	vecho "Checking digest ..."
+	__vecho "Checking digest ..."
 
 	if type -P md5sum > /dev/null; then
-		md5sum -c $digest && r=0
+		local md5sum_output=$(md5sum "${file}")
+		local digest_content=$(< "${digest}")
+		[ "${md5sum_output%%[[:space:]]*}" = "${digest_content%%[[:space:]]*}" ] && r=0
 	elif type -P md5 > /dev/null; then
 		[ "$(md5 -q "${file}")" == "$(cut -d ' ' -f 1 "${digest}")" ] && r=0
 	else
@@ -159,7 +178,7 @@ check_file_signature() {
 
 	if [ ${WEBSYNC_VERIFY_SIGNATURE} != 0 ]; then
 
-		vecho "Checking signature ..."
+		__vecho "Checking signature ..."
 
 		if type -P gpg > /dev/null; then
 			gpg --homedir "${PORTAGE_GPG_DIR}" --verify "$signature" "$file" && r=0
@@ -183,13 +202,25 @@ get_snapshot_timestamp() {
 sync_local() {
 	local file="$1"
 
-	vecho "Syncing local tree ..."
+	__vecho "Syncing local tree ..."
+
+	local ownership="portage:portage"
+	if has usersync ${FEATURES} ; then
+		case "${USERLAND}" in
+			BSD)
+				ownership=$(stat -f '%Su:%Sg' "${repo_location}")
+				;;
+			*)
+				ownership=$(stat -c '%U:%G' "${repo_location}")
+				;;
+		esac
+	fi
 
 	if type -P tarsync > /dev/null ; then
-		local chown_opts="-o portage -g portage"
-		chown portage:portage portage > /dev/null 2>&1 || chown_opts=""
+		local chown_opts="-o ${ownership%:*} -g ${ownership#*:}"
+		chown ${ownership} "${repo_location}" > /dev/null 2>&1 || chown_opts=""
 		if ! tarsync $(vvecho -v) -s 1 ${chown_opts} \
-			-e /distfiles -e /packages -e /local "${file}" "${PORTDIR}"; then
+			-e /distfiles -e /packages -e /local "${file}" "${repo_location}"; then
 			eecho "tarsync failed; tarball is corrupt? (${file})"
 			return 1
 		fi
@@ -201,27 +232,29 @@ sync_local() {
 		fi
 
 		# Free disk space
-		rm -f "${file}"
+		${keep} || rm -f "${file}"
 
-		chown portage:portage portage > /dev/null 2>&1 && \
-			chown -R portage:portage portage
+		local rsync_opts="${PORTAGE_RSYNC_OPTS} ${PORTAGE_RSYNC_EXTRA_OPTS}"
+		if chown ${ownership} portage > /dev/null 2>&1; then
+			chown -R ${ownership} portage
+			rsync_opts+=" --owner --group"
+		fi
 		cd portage
-		rsync -av --progress --stats --delete --delete-after \
-			--exclude='/distfiles' --exclude='/packages' \
-			--exclude='/local' ${PORTAGE_RSYNC_EXTRA_OPTS} . "${PORTDIR%%/}"
+		rsync ${rsync_opts} . "${repo_location%%/}"
 		cd ..
 
-		vecho "Cleaning up ..."
+		__vecho "Cleaning up ..."
 		rm -fr portage
 	fi
 
 	if has metadata-transfer ${FEATURES} ; then
-		vecho "Updating cache ..."
-		emerge --metadata
+		__vecho "Updating cache ..."
+		"${PORTAGE_BIN_PATH}/emerge" --metadata
 	fi
-	[ -x /etc/portage/bin/post_sync ] && /etc/portage/bin/post_sync
+	local post_sync=${PORTAGE_CONFIGROOT}etc/portage/bin/post_sync
+	[ -x "${post_sync}" ] && "${post_sync}"
 	# --quiet suppresses output if there are no relevant news items
-	has news ${FEATURES} && emerge --check-news --quiet
+	has news ${FEATURES} && "${PORTAGE_BIN_PATH}/emerge" --check-news --quiet
 	return 0
 }
 
@@ -251,14 +284,15 @@ do_snapshot() {
 
 	for mirror in ${GENTOO_MIRRORS} ; do
 
-		vecho "Trying to retrieve ${date} snapshot from ${mirror} ..."
+		mirror=${mirror%/}
+		__vecho "Trying to retrieve ${date} snapshot from ${mirror} ..."
 
 		for compression in ${compressions} ; do
 			local file="portage-${date}.tar.${compression}"
 			local digest="${file}.md5sum"
 			local signature="${file}.gpgsig"
 
-			if [ -s "${file}" -a -s "${digest}" -a -s "${signature}" ] ; then
+			if [ -s "${DISTDIR}/${file}" -a -s "${DISTDIR}/${digest}" -a -s "${DISTDIR}/${signature}" ] ; then
 				check_file_digest "${DISTDIR}/${digest}" "${DISTDIR}/${file}" && \
 				check_file_signature "${DISTDIR}/${signature}" "${DISTDIR}/${file}" && \
 				have_files=1
@@ -280,8 +314,8 @@ do_snapshot() {
 			#
 			if [ ${have_files} -eq 1 ]; then
 
-				vecho "Getting snapshot timestamp ..."
-				local snapshot_timestamp=$(get_snapshot_timestamp "${file}")
+				__vecho "Getting snapshot timestamp ..."
+				local snapshot_timestamp=$(get_snapshot_timestamp "${DISTDIR}/${file}")
 
 				if [ ${ignore_timestamp} == 0 ]; then
 					if [ ${snapshot_timestamp} -lt $(get_portage_timestamp) ]; then
@@ -310,7 +344,7 @@ do_snapshot() {
 				#
 				# Remove files and use a different mirror
 				#
-				rm -f "${file}" "${digest}" "${signature}"
+				rm -f "${DISTDIR}/${file}" "${DISTDIR}/${digest}" "${DISTDIR}/${signature}"
 			fi
 		done
 
@@ -318,12 +352,12 @@ do_snapshot() {
 	done
 
 	if [ ${have_files} -eq 1 ]; then
-		sync_local "${file}" && r=0
+		sync_local "${DISTDIR}/${file}" && r=0
 	else
-		vecho "${date} snapshot was not found"
+		__vecho "${date} snapshot was not found"
 	fi
-	
-	rm -f "${file}" "${digest}" "${signature}"
+
+	${keep} || rm -f "${DISTDIR}/${file}" "${DISTDIR}/${digest}" "${DISTDIR}/${signature}"
 	return "${r}"
 }
 
@@ -331,9 +365,9 @@ do_latest_snapshot() {
 	local attempts=0
 	local r=1
 
-	vecho "Fetching most recent snapshot ..."
+	__vecho "Fetching most recent snapshot ..."
 
-	# The snapshot for a given day is generated at 01:45 UTC on the following
+	# The snapshot for a given day is generated at 00:45 UTC on the following
 	# day, so the current day's snapshot (going by UTC time) hasn't been
 	# generated yet.  Therefore, always start by looking for the previous day's
 	# snapshot (for attempts=1, subtract 1 day from the current UTC time).
@@ -349,10 +383,10 @@ do_latest_snapshot() {
 	local start_time=$(get_utc_date_in_seconds)
 	local start_hour=$(get_date_part ${start_time} "%H")
 
-	# Daily snapshots are created at 1:45 AM and are not
-	# available until after 2 AM. Don't waste time trying
+	# Daily snapshots are created at 00:45 and are not
+	# available until after 01:00. Don't waste time trying
 	# to fetch a snapshot before it's been created.
-	if [ ${start_hour} -lt 2 ] ; then
+	if [ ${start_hour} -lt 1 ] ; then
 		(( start_time -= 86400 ))
 	fi
 	local snapshot_date=$(get_date_part ${start_time} "%Y%m%d")
@@ -361,8 +395,8 @@ do_latest_snapshot() {
 	while (( ${attempts} <  40 )) ; do
 		(( attempts++ ))
 		(( snapshot_date_seconds -= 86400 ))
-		# snapshots are created at 1:45 AM
-		(( approx_snapshot_time = snapshot_date_seconds + 86400 + 6300 ))
+		# snapshots are created at 00:45
+		(( approx_snapshot_time = snapshot_date_seconds + 86400 + 2700 ))
 		(( timestamp_difference = existing_timestamp - approx_snapshot_time ))
 		[ ${timestamp_difference} -lt 0 ] && (( timestamp_difference = -1 * timestamp_difference ))
 		snapshot_date=$(get_date_part ${snapshot_date_seconds} "%Y%m%d")
@@ -388,7 +422,7 @@ do_latest_snapshot() {
 				"snapshot. In order to force sync," \
 				"use the --revert option or remove" \
 				"the timestamp file located at" \
-				"'${PORTDIR}/metadata/timestamp.x'." | fmt -w 70 | \
+				"'${repo_location}/metadata/timestamp.x'." | fmt -w 70 | \
 				while read -r line ; do
 					ewarn "${line}"
 				done
@@ -408,9 +442,10 @@ do_latest_snapshot() {
 usage() {
 	cat <<-EOF
 	Usage: $0 [options]
-	
+
 	Options:
 	  --revert=yyyymmdd   Revert to snapshot
+	  -k, --keep          Keep snapshots in DISTDIR (don't delete)
 	  -q, --quiet         Only output errors
 	  -v, --verbose       Enable verbose output
 	  -x, --debug         Enable debug output
@@ -427,14 +462,12 @@ usage() {
 main() {
 	local arg
 	local revert_date
-	
-	[ ! -d "${DISTDIR}" ] && mkdir -p "${DISTDIR}"
-	cd "${DISTDIR}"
 
 	for arg in "$@" ; do
 		local v=${arg#*=}
 		case ${arg} in
 			-h|--help)    usage ;;
+			-k|--keep)    keep=true ;;
 			-q|--quiet)   PORTAGE_QUIET=1 ;;
 			-v|--verbose) do_verbose=1 ;;
 			-x|--debug)   do_debug=1 ;;
@@ -443,16 +476,39 @@ main() {
 		esac
 	done
 
+	[[ -d ${repo_location} ]] || mkdir -p "${repo_location}"
+	if [[ ! -w ${repo_location} ]] ; then
+		eecho "Repository '${repo_name}' is not writable: ${repo_location}"
+		exit 1
+	fi
+
+	[[ -d ${PORTAGE_TMPDIR}/portage ]] || mkdir -p "${PORTAGE_TMPDIR}/portage"
+	TMPDIR=$(mktemp -d "${PORTAGE_TMPDIR}/portage/webrsync-XXXXXX")
+	if [[ ! -w ${TMPDIR} ]] ; then
+		eecho "TMPDIR is not writable: ${TMPDIR}"
+		exit 1
+	fi
+	trap 'cd / ; rm -rf "${TMPDIR}"' EXIT
+	cd "${TMPDIR}" || exit 1
+
+	${keep} || DISTDIR=${TMPDIR}
+	[ ! -d "${DISTDIR}" ] && mkdir -p "${DISTDIR}"
+
+	if ${keep} && [[ ! -w ${DISTDIR} ]] ; then
+		eecho "DISTDIR is not writable: ${DISTDIR}"
+		exit 1
+	fi
+
 	# This is a sanity check to help prevent people like funtoo users
 	# from accidentally wiping out their git tree.
-	if [[ -n $SYNC && ${SYNC#rsync:} = $SYNC ]] ; then
-		echo "The current SYNC variable setting does not refer to an rsync URI:" >&2
+	if [[ -n ${repo_sync_type} && ${repo_sync_type} != rsync ]] ; then
+		echo "The current sync-type attribute of repository 'gentoo' is not set to 'rsync':" >&2
 		echo >&2
-		echo "  SYNC=$SYNC" >&2
+		echo "  sync-type=${repo_sync_type}" >&2
 		echo >&2
 		echo "If you intend to use emerge-webrsync then please" >&2
-		echo "adjust SYNC to refer to an rsync URI." >&2
-		echo "emerge-webrsync exiting due to abnormal SYNC setting." >&2
+		echo "adjust sync-type and sync-uri attributes to refer to rsync." >&2
+		echo "emerge-webrsync exiting due to abnormal sync-type setting." >&2
 		exit 1
 	fi
 
