bin: style tweaks
Signed-off-by: Sam James <sam@gentoo.org>

diff --git a/bin/ebuild-helpers/dohtml b/bin/ebuild-helpers/dohtml
--- a/bin/ebuild-helpers/dohtml
+++ b/bin/ebuild-helpers/dohtml
@@ -5,22 +5,22 @@
 source "${PORTAGE_BIN_PATH}"/isolated-functions.sh || exit 1
 
 if ! ___eapi_has_dohtml; then
-	die "'${0##*/}' has been banned for EAPI '$EAPI'"
+	die "'${0##*/}' has been banned for EAPI '${EAPI}'"
 	exit 1
 fi
 
 if ___eapi_has_dohtml_deprecated; then
-	eqawarn "'${0##*/}' is deprecated in EAPI '$EAPI'"
+	eqawarn "'${0##*/}' is deprecated in EAPI '${EAPI}'"
 fi
 
 # Use safe cwd, avoiding unsafe import for bug #469338.
 export __PORTAGE_HELPER_CWD=${PWD}
 cd "${PORTAGE_PYM_PATH}" || die
 PYTHONPATH=${PORTAGE_PYTHONPATH:-${PORTAGE_PYM_PATH}} \
-	"${PORTAGE_PYTHON:-/usr/bin/python}" "$PORTAGE_BIN_PATH/dohtml.py" "$@"
+	"${PORTAGE_PYTHON:-/usr/bin/python}" "${PORTAGE_BIN_PATH}/dohtml.py" "$@"
 
 ret=$?
 # Restore cwd for display by __helpers_die
 cd "${__PORTAGE_HELPER_CWD}"
-[[ $ret -ne 0 ]] && __helpers_die "${0##*/} failed"
-exit $ret
+[[ ${ret} -ne 0 ]] && __helpers_die "${0##*/} failed"
+exit ${ret}
diff --git a/bin/ebuild-helpers/fowners b/bin/ebuild-helpers/fowners
--- a/bin/ebuild-helpers/fowners
+++ b/bin/ebuild-helpers/fowners
@@ -11,10 +11,12 @@ fi
 got_owner=
 for arg; do
 	[[ ${arg} == -* ]] && continue
+
 	if [[ ! ${got_owner} ]]; then
 		got_owner=1
 		continue
 	fi
+
 	if [[ ${arg} != /* ]]; then
 		eqawarn "Relative path passed to '${0##*/}': ${arg}"
 		eqawarn "This is unsupported. Please use 'chown' when you need to work on files"
@@ -29,5 +31,5 @@ slash="/"
 chown "${@/#${slash}/${ED%/}${slash}}"
 ret=$?
 
-[[ $ret -ne 0 ]] && __helpers_die "${0##*/} failed"
-exit $ret
+[[ ${ret} -ne 0 ]] && __helpers_die "${0##*/} failed"
+exit ${ret}
diff --git a/bin/ebuild-helpers/fperms b/bin/ebuild-helpers/fperms
--- a/bin/ebuild-helpers/fperms
+++ b/bin/ebuild-helpers/fperms
@@ -12,10 +12,12 @@ got_mode=
 for arg; do
 	# - can either be an option or a mode string
 	[[ ${arg} == -* && ${arg} != -[ugorwxXst] ]] && continue
+
 	if [[ ! ${got_mode} ]]; then
 		got_mode=1
 		continue
 	fi
+
 	if [[ ${arg} != /* ]]; then
 		eqawarn "Relative path passed to '${0##*/}': ${arg}"
 		eqawarn "This is unsupported. Please use 'chmod' when you need to work on files"
@@ -28,5 +30,5 @@ done
 slash="/"
 chmod "${@/#${slash}/${ED%/}${slash}}"
 ret=$?
-[[ $ret -ne 0 ]] && __helpers_die "${0##*/} failed"
-exit $ret
+[[ ${ret} -ne 0 ]] && __helpers_die "${0##*/} failed"
+exit ${ret}
