* In helpers_die arguments, display ${0##*/} instead of $0 since $0   is needlessly long. * When calling helpers_die from a function, use ${FUNCNAME[0]} in   arguments instead of $0.

diff --git a/bin/ebuild-helpers/doinfo b/bin/ebuild-helpers/doinfo
--- a/bin/ebuild-helpers/doinfo
+++ b/bin/ebuild-helpers/doinfo
@@ -10,7 +10,7 @@ if [[ -z $1 ]] ; then
 fi
 
 if [[ ! -d ${D}usr/share/info ]] ; then
-	install -d "${D}usr/share/info" || { helpers_die "$0: failed to install ${D}usr/share/info"; exit 1; }
+	install -d "${D}usr/share/info" || { helpers_die "${0##*/}: failed to install ${D}usr/share/info"; exit 1; }
 fi
 
 install -m0644 "$@" "${D}usr/share/info"
@@ -19,6 +19,6 @@ if [ $rval -ne 0 ] ; then
 	for x in "$@" ; do
 		[ -e "$x" ] || echo "!!! ${0##*/}: $x does not exist" 1>&2
 	done
-	helpers_die "$0 failed"
+	helpers_die "${0##*/} failed"
 fi
 exit $rval
