bin: Rename all _E_*DESTTREE_ variables to __E_*DESTTREE
The __* namespace is reserved for package manager use.

Signed-off-by: Ulrich Müller <ulm@gentoo.org>

diff --git a/bin/ebuild-helpers/dosbin b/bin/ebuild-helpers/dosbin
--- a/bin/ebuild-helpers/dosbin
+++ b/bin/ebuild-helpers/dosbin
@@ -1,5 +1,5 @@
 #!/usr/bin/env bash
-# Copyright 1999-2018 Gentoo Foundation
+# Copyright 1999-2023 Gentoo Authors
 # Distributed under the terms of the GNU General Public License v2
 
 source "${PORTAGE_BIN_PATH}"/isolated-functions.sh || exit 1
@@ -18,18 +18,18 @@ if ! ___eapi_has_DESTTREE_INSDESTTREE; then
 		die "${0##*/}: \${DESTTREE} has been banned for EAPI '${EAPI}'; use 'into' instead"
 else
 	# backwards compatibility
-	_E_DESTTREE_=${DESTTREE}
+	__E_DESTTREE=${DESTTREE}
 fi
 
-if [[ ! -d ${ED%/}/${_E_DESTTREE_#/}/sbin ]] ; then
-	install -d "${ED%/}/${_E_DESTTREE_#/}/sbin" || { __helpers_die "${0##*/}: failed to install ${ED%/}/${_E_DESTTREE_#/}/sbin"; exit 2; }
+if [[ ! -d ${ED%/}/${__E_DESTTREE#/}/sbin ]] ; then
+	install -d "${ED%/}/${__E_DESTTREE#/}/sbin" || { __helpers_die "${0##*/}: failed to install ${ED%/}/${__E_DESTTREE#/}/sbin"; exit 2; }
 fi
 
 ret=0
 
 for x in "$@" ; do
 	if [[ -e ${x} ]] ; then
-		install -m0755 -o ${PORTAGE_INST_UID:-0} -g ${PORTAGE_INST_GID:-0} "${x}" "${ED%/}/${_E_DESTTREE_#/}/sbin"
+		install -m0755 -o ${PORTAGE_INST_UID:-0} -g ${PORTAGE_INST_GID:-0} "${x}" "${ED%/}/${__E_DESTTREE#/}/sbin"
 	else
 		echo "!!! ${0##*/}: ${x} does not exist" 1>&2
 		false
