bin: style tweaks
Signed-off-by: Sam James <sam@gentoo.org>

diff --git a/bin/ebuild-helpers/dosym b/bin/ebuild-helpers/dosym
--- a/bin/ebuild-helpers/dosym
+++ b/bin/ebuild-helpers/dosym
@@ -5,7 +5,7 @@
 source "${PORTAGE_BIN_PATH}"/isolated-functions.sh || exit 1
 
 option_r=
-if ___eapi_has_dosym_r && [[ $1 == -r ]]; then
+if ___eapi_has_dosym_r && [[ ${1} == -r ]]; then
 	option_r=t
 	shift
 fi
@@ -24,7 +24,7 @@ if [[ ${2} == */ ]] || [[ -d ${ED%/}/${2#/} && ! -L ${ED%/}/${2#/} ]] ; then
 	__helpers_die "${0##*/}: dosym target omits basename: '${2}'"
 fi
 
-target=$1
+target=${1}
 
 if [[ ${option_r} ]]; then
 	# Transparent bash-only replacement for GNU "realpath -m -s".
@@ -33,8 +33,8 @@ if [[ ${option_r} ]]; then
 	dosym_canonicalize() {
 		local path slash i prev out IFS=/
 
-		path=( $1 )
-		[[ $1 == /* ]] && slash=/
+		path=( ${1} )
+		[[ ${1} == /* ]] && slash=/
 
 		while true; do
 			# Find first instance of non-".." path component followed by "..",
@@ -87,6 +87,6 @@ destdir=${2%/*}
 [[ ! -d ${ED%/}/${destdir#/} ]] && dodir "${destdir}"
 ln -snf "${target}" "${ED%/}/${2#/}"
 
-ret=$?
-[[ $ret -ne 0 ]] && __helpers_die "${0##*/} failed"
-exit $ret
+ret=${?}
+[[ ${ret} -ne 0 ]] && __helpers_die "${0##*/} failed"
+exit ${ret}
